# Site settings
title: David Board
email: service@cprteam.org
description: > # this means to ignore newlines until "baseurl:"
  David Dashboard aka. David Board.
  A CPRTeam System Dashboard for CPRTeam internal use.
  by Haraguroicha @ CPRTeam (c) 2015.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://board.cprteam.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  CPRTeam
timezone: Asia/Taipei
exclude: [ "CNAME", "david-board.sublime-project" ]

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

# Build settings
markdown: kramdown

kramdown:
  input: GFM
